springdoc.api-docs.path=/api/docs
springdoc.swagger-ui.path=/api
app.version=@project.version@

spring.servlet.multipart.max-file-size=-1
spring.servlet.multipart.max-request-size=-1

app.cors.allowed-origin-patterns[0]=https://ide.florianbecker.eu
app.cors.allowed-origin-patterns[1]=http://localhost:*
app.cors.allowed-origin-patterns[2]=https://localhost:*
app.cors.allowed-origin-patterns[3]=http://127.0.0.1:*
app.cors.allowed-origin-patterns[4]=https://127.0.0.1:*
app.cors.allow-credentials=true
