permissions:
    packages: write

name: Build and publish a Docker image to ghcr.io
on:
    # publish on pushes to the main branch (image tagged as "latest")
    push:
        branches:
            - main
            - master
env:
  REGISTRY: ghcr.io

jobs:
  docker_publish_X86:
      runs-on: "ubuntu-20.04"

      permissions:
          contents: read
          packages: write

      steps:
          - uses: actions/checkout@v4

          - name: Read Maven package version
            id: maven_version
            run: echo "::set-output name=PACKAGE_VERSION::$(mvn help:evaluate -Dexpression=project.version -q -DforceStdout)"
          
          - name: downcase REPO
            run: |
              echo "REPO=${GITHUB_REPOSITORY,,}" >>${GITHUB_ENV}

          - name: Set up Docker Buildx
            uses: docker/setup-buildx-action@v3

          - name: Log in to the Container registry
            uses: docker/login-action@v3
            with:
              registry: ${{ env.REGISTRY }}
              username: ${{ github.actor }}
              password: ${{ secrets.GITHUB_TOKEN }}
          
          - name: Extract metadata (tags, labels) for Docker
            id: meta
            uses: docker/metadata-action@v5
            with:
              images: ${{ env.REGISTRY }}/${{ env.REPO }}

          - name: Build and push Docker image
            uses: docker/build-push-action@v5
            with:
              context: .
              push: true
              platforms: linux/amd64
              tags: |
                  ${{ env.REGISTRY }}/${{ env.REPO }}:${{ steps.maven_version.outputs.PACKAGE_VERSION }}
                  ${{ env.REGISTRY }}/${{ env.REPO }}:latest
              build-args: |
                  GITHUB_ACTOR=${{ github.actor }}
                  GITHUB_ACCESS_TOKEN=${{ secrets.GITHUB_TOKEN }}

  docker_publish_ARM:
      runs-on: "ubuntu-20.04"

      permissions:
          contents: read
          packages: write

      steps:
          - uses: actions/checkout@v4

          - name: Read Maven package version
            id: maven_version
            run: echo "::set-output name=PACKAGE_VERSION::$(mvn help:evaluate -Dexpression=project.version -q -DforceStdout)"
          
          - name: downcase REPO
            run: |
              echo "REPO=${GITHUB_REPOSITORY,,}" >>${GITHUB_ENV}

          - name: Set up Docker Buildx
            uses: docker/setup-buildx-action@v3

          - name: Log in to the Container registry
            uses: docker/login-action@v3
            with:
              registry: ${{ env.REGISTRY }}
              username: ${{ github.actor }}
              password: ${{ secrets.GITHUB_TOKEN }}
          
          - name: Extract metadata (tags, labels) for Docker
            id: meta
            uses: docker/metadata-action@v5
            with:
              images: ${{ env.REGISTRY }}/${{ env.REPO }}

          - name: Build and push Docker image
            uses: docker/build-push-action@v5
            with:
              context: .
              push: true
              platforms: linux/arm64
              tags: |
                  ${{ env.REGISTRY }}/${{ env.REPO }}:${{ steps.maven_version.outputs.PACKAGE_VERSION }}
                  ${{ env.REGISTRY }}/${{ env.REPO }}:latest
              build-args: |
                  GITHUB_ACTOR=${{ github.actor }}
                  GITHUB_ACCESS_TOKEN=${{ secrets.GITHUB_TOKEN }}
